### ISSUE TITLE
is these packages are available to used ?

### ISSUE THREAD

**Issue by chanphiromsok** [expo/dev-plugins#10]

**Comment by Kudo** [comment]
hi there! i wrote the installation guide in each packages's README, e.g. https://github.com/expo/dev-plugins/tree/main/packages/apollo-client

hope that helps for you. thanks!

**Comment by chanphiromsok** [comment]
> hi there! i wrote the installation guide in each packages's README, e.g. https://github.com/expo/dev-plugins/tree/main/packages/apollo-client
> 
> 
> 
> hope that helps for you. thanks!
thanks you

**Comment by chanphiromsok** [comment]
I got an error when running the application on Expo sdk 49
<img width="1135" alt="image" src="https://github.com/expo/dev-plugins/assets/65760336/d0206911-bf24-4aba-9900-274ab4c7ff73">

**Comment by Kudo** [comment]
devtools plugins are available from sdk 50: https://expo.dev/changelog/2023/12-12-sdk-50-beta

**Comment by chanphiromsok** [comment]
> devtools plugins are available from sdk 50: https://expo.dev/changelog/2023/12-12-sdk-50-beta

thanks you
