### ISSUE TITLE
Inlined process typings causing conflicts

### ISSUE THREAD

**Issue by sdacunha** [expo/dev-plugins#16]
Hi, appreciate the teams work setting up these dev plugins - it has helped our transition away from Flipper.

One issue however, is that since the process env definitions were inlined, we are getting failures in CI such as these:
![Screenshot 2023-12-28 at 5 23 52 PM](https://github.com/expo/dev-plugins/assets/6006129/06afb8c2-a8c3-4792-a304-9c59d3660859)
 
Here is the offending type definition:
https://github.com/expo/dev-plugins/blame/917d64066815e8cdc0b59641bae44b4abc07c0ca/packages/apollo-client/src/index.ts#L1

With the changes to how environment variables are loaded out of the box in SDK 49, this may cause issues for other users and I wanted to help them avoid spending hours trying to find the source of the error.

I currently patch the library by including @types/node and including it in the tsconfig.

**Comment by Kudo** [comment]
thanks for reporting the issue. please try out `@dev-plugins/apollo-client@0.0.5` and let me know whether it works for you.
