### ISSUE TITLE
@dev-plugin/async-storage inline editing cursor jump

### ISSUE THREAD

**Issue by plrdev** [expo/dev-plugins#23]
Async storage devtools have an option to inline edit the value, but it updates the value after each keystroke, which sets the cursor at the beginning of the text input. The result is typing backwards!

For example, trying to type `testing` results into: 

<img width="800" alt="image" src="https://github.com/expo/dev-plugins/assets/2563512/c328c7d7-8ea9-4aae-9ed3-ed9c06b91ac4">

React probably re-renders after the value change and resets the cursor.

**Comment by jthoward64** [comment]
Yeah I'd had that issue before and though I'd fixed it, I will take a look and see what's going on tonight or tommorow.
