### ISSUE TITLE
How to run examples

### ISSUE THREAD

**Issue by ddennis** [expo/dev-plugins#25]
Sorry for being stupid. I can't get the examples to run.

- I assume i can go to **apps/example** and do **npm install** - but this fails
- If i go to **packages/react-navigation** and do **npm install** it also fails

> 
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree             
> npm ERR!                                                        
> npm ERR! While resolving: @dev-plugins/apollo-client-webui@0.0.5
> npm ERR! Found: react@18.2.0                                    
> npm ERR! node_modules/react
> npm ERR!   dev react@"18.2.0" from @dev-plugins/apollo-client-webui@0.0.5
> npm ERR!   packages/apollo-client/webui
> npm ERR!     @dev-plugins/apollo-client-webui@0.0.5
> npm ERR!     node_modules/@dev-plugins/apollo-client-webui
> npm ERR!       workspace packages\apollo-client\webui from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^17.0.0 || ^16.3.0 || ^15.5.4" from react-json-view@1.21.3
> npm ERR! node_modules/react-json-view
> npm ERR!   dev react-json-view@"^1.21.3" from @dev-plugins/apollo-client-webui@0.0.5
> npm ERR!   packages/apollo-client/webui
> npm ERR!     @dev-plugins/apollo-client-webui@0.0.5
> npm ERR!     node_modules/@dev-plugins/apollo-client-webui
> npm ERR!       workspace packages\apollo-client\webui from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR!
> npm ERR! For a full report see:
>

**Comment by Kudo** [comment]
hi there. this is the steps to run example

```sh
$ git clone https://github.com/expo/dev-plugins.git
$ cd dev-plugins
$ yarn
$ cd apps/example
$ yarn ios
```

i'll also update the readme for running example. thanks!

**Comment by SeanDunford** [comment]
Only posting so other can find. `npm install` won't work, you must use `yarn`

```
npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: @dev-plugins/apollo-client-webui@0.1.0
npm error Found: react@18.3.1
npm error node_modules/react
npm error   dev react@"18.3.1" from @dev-plugins/apollo-client-webui@0.1.0
npm error   packages/apollo-client/webui
npm error     @dev-plugins/apollo-client-webui@0.1.0
npm error     node_modules/@dev-plugins/apollo-client-webui
npm error       workspace packages/apollo-client/webui from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^17.0.0 || ^16.3.0 || ^15.5.4" from react-json-view@1.21.3
npm error node_modules/react-json-view
npm error   dev react-json-view@"^1.21.3" from @dev-plugins/apollo-client-webui@0.1.0
npm error   packages/apollo-client/webui
npm error     @dev-plugins/apollo-client-webui@0.1.0
npm error     node_modules/@dev-plugins/apollo-client-webui
npm error       workspace packages/apollo-client/webui from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error ~/.npm/_logs/2024-11-18T19_49_37_641Z-eresolve-report.txt
npm error A complete log of this run can be found in:~/.npm/_logs/2024-11-18T19_49_37_641Z-debug-0.log
```

**Comment by Kudo** [comment]
thanks. we now migrate from yarn to bun in this repo. also updated README that i forgot to update previously
