### ISSUE TITLE
store.addDidFinishTransactionListener is not a function error when using TinyBase with Zustand.

### ISSUE THREAD

**Issue by c2tarun** [expo/dev-plugins#34]
Hey all,

I am trying to use tinybase dev-plugin to visualize state change in a Zustand store I have. After following instructions in README I am getting following error:

In console:
```
 ERROR  TypeError: store.addDidFinishTransactionListener is not a function (it is undefined)

This error is located at:
    in App (at withDevTools.ios.js:25)
    in withDevTools(App) (at renderApplication.js:57)
    in RCTView (at View.js:116)
    in View (at AppContainer.js:127)
    in RCTView (at View.js:116)
    in View (at AppContainer.js:155)
    in AppContainer (at renderApplication.js:50)
    in main(RootComponent) (at renderApplication.js:67), js engine: hermes
 ERROR  TypeError: store.addDidFinishTransactionListener is not a function (it is undefined)

This error is located at:
    in App (at withDevTools.ios.js:25)
    in withDevTools(App) (at renderApplication.js:57)
    in RCTView (at View.js:116)
    in View (at AppContainer.js:127)
    in RCTView (at View.js:116)
    in View (at AppContainer.js:155)
    in AppContainer (at renderApplication.js:50)
    in main(RootComponent) (at renderApplication.js:67), js engine: hermes
```

In Expo Go app:
![image](https://github.com/expo/dev-plugins/assets/1129670/e88aab1f-d370-4703-979e-b51ef8a9785b)

I created a sample git repository with minimal code to reproduce the issue. Any help on how to make this work would be really appreciated :).

https://github.com/c2tarun/TinyBaseDemo

Thanks

**Comment by erenilufer** [comment]
Tinybase plugin is not compatible with zustand. `useTinyBaseDevTools(useCounterStore);` in this line, you are passing zustand store object to the plugin. Since zustand StoreApi doesn't have `addDidFinishTransactionListener`, you are getting the error. You need a compatible plugin to go ahead. It seems like it hasn't been implemented yet. @c2tarun

**Comment by Kudo** [comment]
hi there! as @erenilufer pointed out, the `@dev-plugins/tinybase` for tinybase and you should pass a [tinybase store with the addDidFinishTransactionListener function](https://tinybase.org/api/store/interfaces/store/store/methods/listener/adddidfinishtransactionlistener/).
