### ISSUE TITLE
react query dev tools not working with Expo 52

### ISSUE THREAD

**Issue by brunocentanaro** [expo/dev-plugins#50]
# Steps to Reproduce
Initialize a new Expo project with TypeScript:
1. npx create-expo-app --template blank-typescript
2. Install React Query dependencies: npx expo install @tanstack/react-query and npm i --dev @dev-plugins/react-query
3. Set up queryClient and wrap your application with QueryClientProvider.
4. Run a query in your app and try to inspect it using React Query Dev Tools in the browser.

# Expected Behavior
React Query Dev Tools should display the query data in the browser as expected.

# Actual Behavior
The Dev Tools UI loads correctly in the browser, but the data for the query appears empty, even though the query is running in the app.

# Environment
- Expo: 52.0.4
- React Native: 0.76.1
- @tanstack/react-query: 5.59.20
- @dev-plugins/react-query: 0.0.7

**Comment by Kudo** [comment]
thanks for catching the problem. i've published `@dev-plugins/react-query@0.1.0` to support sdk 52. could you check whether if helps?

**Comment by brunocentanaro** [comment]
Yes it works! Thanks
