### ISSUE TITLE
@dev-plugins/react-query - It stopped working without doing anything

### ISSUE THREAD

**Issue by rizikolik** [expo/dev-plugins#52]
Hi,
I am using     "@dev-plugins/react-query": "^0.1.0" and expo 51.0.38.
Suddenly without doing anything and without adding a new package dev plugin for react query stopped working.
It opens the browser but its always empty.
Any suggestion ?

**Comment by Kudo** [comment]
@rizikolik the `@dev-plugins/react-query@0.1.0` is for sdk 52. you should have the peer dependency warning
```
warning " > @dev-plugins/react-query@0.1.0" has unmet peer dependency "expo@^52.0.0".
```

please use tilde version `@dev-plugins/react-query@~0.0.1` if you are still on sdk 51. sorry for the hassle, we would try to find a way to deal with the dependency management better.

**Comment by rizikolik** [comment]
Thanks a lot @Kudo !
